import os
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def create_document():
    doc = Document()

    # Title
    title = doc.add_heading('Hate Comment Detection - Source Code Overview', 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    doc.add_paragraph('This document provides an explanation of each file within the "src" folder of the project, detailing its purpose and functionality.')

    files_info = [
        {
            "name": "api.py",
            "desc": "Implements the REST API backend using FastAPI. It defines endpoints (like '/predict') that receive text input, invoke the model, and return classification results (Label, Confidence). It acts as the interface between the trained model and external applications."
        },
        {
            "name": "inference.py",
            "desc": "Contains the 'HateCommentClassifier' class, which encapsulates the logic for loading the model/tokenizer and performing inference. It handles text tokenization, model forward pass, and converting logits to probability scores."
        },
        {
            "name": "data.py",
            "desc": "Responsible for loading the 'hatexplain' dataset directly from the Hugging Face Hub. It includes functions to load specific splits (train/val/test) and inspect the dataset structure."
        },
        {
            "name": "export_saved_dataset.py",
            "desc": "A utility script to load a dataset that has been saved to disk (in Hugging Face Dataset format) and export it to common formats like CSV and JSONL. This is useful for inspecting data in other tools or sharing processed data."
        },
        {
            "name": "fetch_and_save_dataset.py",
            "desc": "Downloads the 'hatexplain' dataset from the Hugging Face Hub and saves it locally to disk. This ensures that the data is available offline and doesn't need to be re-downloaded for every run."
        },
        {
            "name": "load_csv_dataset.py",
            "desc": "Handles loading of local raw CSV datasets (specifically 'labeled_data.csv'). It reads the CSV, selects relevant columns (tweet/text and class/label), and converts the data into a Hugging Face Dataset object for compatibility with the training pipeline."
        },
        {
            "name": "preprocess.py",
            "desc": "Contains core helper functions for text preprocessing. It includes 'clean_text' for tasks like lowercasing, removing URLs, usernames, and extra whitespace, and 'detect_text_column' to heuristically identify the text column in a dataset."
        },
        {
            "name": "preprocess_dataset.py",
            "desc": "A comprehensive script for advanced data preprocessing. It orchestrates the entire data preparation workflow: loading data, applying cleaning (handling emojis, contractions, stopwords), balancing classes (using oversampling or undersampling), splitting the data into train/validation/test sets, and saving the final processed files."
        },
        {
            "name": "statistical_analysis.py",
            "desc": "Performs in-depth statistical analysis of the dataset. It calculates metrics like class distribution, text character/word counts, and token lengths. It also generates visualizations (histograms, pie charts) and an HTML report to help understand data quality and characteristics."
        },
        {
            "name": "train.py",
            "desc": "A general-purpose training script using the Hugging Face Trainer API. It supports loading datasets (from HF or CSV), tokenization, and fine-tuning transformer models (like DistilBERT). It is flexible and auto-detects column names."
        },
        {
            "name": "train_pytorch.py",
            "desc": "A specialized training script tailored for this project's specific workflow. It is designed to work seamlessly with the preprocessed splits generated by 'preprocess_dataset.py'. It defines specific metrics (Accuracy, F1, Precision, Recall) and handles a 3-class classification problem."
        },
        {
            "name": "__init__.py",
            "desc": "An initialization file that marks the 'src' directory as a Python package, allowing its modules to be imported elsewhere in the project."
        }
    ]

    for file in files_info:
        # File Name Heading
        h = doc.add_heading(file["name"], level=1)
        run = h.runs[0]
        run.font.color.rgb = RGBColor(0, 50, 100) # Dark blue

        # Description
        p = doc.add_paragraph(file["desc"])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

    # Technologies Section
    doc.add_page_break()
    title_tech = doc.add_heading('Key Technologies', 0)
    title_tech.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_paragraph('This section explains the core technologies used to serve the model (found in src/api.py).')

    tech_info = [
        {
            "name": "DistilBERT",
            "desc": "A smaller, faster, cheaper, and lighter version of the BERT (Bidirectional Encoder Representations from Transformers) model. It retains 97% of BERT's performance while being 40% smaller and 60% faster. In this project, 'distilbert-base-uncased' serves as the core engine effectively 'understanding' the context of comments. We fine-tune this pre-trained model on our specific hate speech dataset (Transfer Learning) to classify text into our 3 categories."
        },
        {
            "name": "FastAPI",
            "desc": "A modern, fast (high-performance) web framework for building APIs with Python 3.7+ based on standard Python type hints. In this project, it is used to create the /predict endpoint, handle incoming JSON requests, validate data structures, and return JSON responses. It is chosen for its speed and automatic Swagger UI documentation generation."
        },
        {
            "name": "Uvicorn",
            "desc": "An ASGI (Asynchronous Server Gateway Interface) web server implementation for Python. While FastAPI builds the application logic, Uvicorn is the server that actually runs it. It processes HTTP requests and passes them to the FastAPI application. It is lightning-fast and supports asynchronous capabilities, making it ideal for ML model serving."
        }
    ]

    for item in tech_info:
        h = doc.add_heading(item["name"], level=1)
        run = h.runs[0]
        run.font.color.rgb = RGBColor(0, 100, 50) # Dark Green

        p = doc.add_paragraph(item["desc"])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

    # Models Section
    doc.add_page_break()
    title_models = doc.add_heading('Models Directory Structure', 0)
    title_models.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_paragraph('This section details the standard files found within a trained Hugging Face model directory (e.g., inside "models/hate-detection-balanced").')

    models_info = [
        {
            "name": "config.json",
            "desc": "Contains the configuration of the model architecture. It specifies parameters such as the number of layers (hidden states), attention heads, vocab size, and mapping of label IDs to class names (e.g., LABEL_0 -> Hate Speech)."
        },
        {
            "name": "model.safetensors",
            "desc": "The trained model weights saved in the SafeTensors format. This includes all the learnable parameters (weights and biases) of the neural network. It is safer and faster to load than the traditional 'pytorch_model.bin' pickle file."
        },
        {
            "name": "tokenizer.json",
            "desc": "A single file containing the complete tokenizer object, including the vocabulary and the tokenization model (e.g., WordPiece). Functionally, the tokenizer is the bridge between raw text and the model. It is used to: 1) Break text into manageable subwords (tokens), 2) Convert these tokens into numerical IDs that the model understands, and 3) Format inputs with special tokens ([CLS], [SEP]) and padding/truncation."
        },
        {
            "name": "vocab.txt",
            "desc": "The vocabulary file containing the mapping between tokens and their integer IDs. For DistilBERT, this list includes all the words and subwords the model understands."
        },
        {
            "name": "tokenizer_config.json",
            "desc": "Stores configuration details for the tokenizer, such as which class to use (e.g., 'DistilBertTokenizerFast'), and specific settings like casing (do_lower_case=True) or maximum length."
        },
        {
            "name": "special_tokens_map.json",
            "desc": "Defines special tokens used by the model for specific purposes, such as [CLS] (classification start), [SEP] (separator), [PAD] (padding), and [UNK] (unknown token)."
        },
        {
            "name": "training_args.bin",
            "desc": "A binary file containing the TrainingArguments object used during the training process. It preserves hyperparameters like learning rate, batch size, and number of epochs for reproducibility."
        },
        {
            "name": "checkpoint-XXXX/",
            "desc": "Directories (e.g., checkpoint-500) saved periodically during training. These act as full 'save states' for the training process. Inside each checkpoint, you will find: A copy of the model contents (config, weights), the tokenizer files, AND the training state files (`optimizer.pt`, `scheduler.pt`, `trainer_state.json`). `optimizer.pt` saves the momentum and gradients of the optimizer. `scheduler.pt` saves the current learning rate. These files are crucial for resuming training exactly where it paused."
        },
        {
            "name": "runs/",
            "desc": "Contains TensorBoard logs (events files). These record metrics like loss and accuracy over time, which can be visualized to monitor training progress."
        }
    ]

    for item in models_info:
        # File Name Heading
        h = doc.add_heading(item["name"], level=1)
        run = h.runs[0]
        run.font.color.rgb = RGBColor(100, 0, 0) # Dark Red for distinction

        # Description
        p = doc.add_paragraph(item["desc"])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

    # Frontend Section
    doc.add_page_break()
    title_ui = doc.add_heading('Frontend Architecture (UI)', 0)
    title_ui.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_paragraph('This section details the structure of the React-based User Interface located in the "ui" folder. It uses modern tools like Vite, TailwindCSS (v4), and Framer Motion.')

    ui_files_info = [
        {
            "name": "App.jsx",
            "desc": "The main entry point of the React application's UI. It serves as the container for the entire page, setting up the global layout (hero section, headers, background gradients) and managing the application state (e.g., storing the analysis result data fetched from the API)."
        },
        {
            "name": "main.jsx",
            "desc": "The root JavaScript file that mounts the React application onto the DOM (HTML). It wraps the <App /> component within React.StrictMode."
        },
        {
            "name": "index.css",
            "desc": "The global stylesheet. We use this to configure TailwindCSS v4 using specific directives (@import 'tailwindcss') and define custom theme variables (colors like --color-dark-900). It also implements a custom scrollbar to match the dark theme."
        },
        {
            "name": "vite.config.js",
            "desc": "Configuration file for Vite (the build tool). It registers plugins like '@vitejs/plugin-react' for React support and '@tailwindcss/vite' for processing TailwindCSS styles efficiently."
        },
        {
            "name": "src/components/SearchBar.jsx",
            "desc": "A reusable component that renders the stylish URL input field. It features complex animations (Framer Motion) for entry effects and uses a 'glassmorphism' aesthetic. It handles user input and triggers the 'onAnalyze' callback when the button is clicked."
        },
        {
            "name": "src/components/AnalysisDashboard.jsx",
            "desc": "The core visualization component. It accepts the analysis data and renders: 1) Overall Toxicity Score (Big Number), 2) A Donut/Pie Chart using 'recharts' to show the ratio of Safe/Toxic comments, and 3) A filtered list of comments."
        },
        {
            "name": "src/components/CommentCard.jsx",
            "desc": "Displays a single YouTube comment. It applies color-coded badges based on the toxicity label (Green for Safe, Red for Hate Speech). It also implements a 'blur' feature where toxic comments are hidden by default to protect the user, with an eye icon to toggle visibility."
        }
    ]

    for item in ui_files_info:
        h = doc.add_heading(item["name"], level=1)
        run = h.runs[0]
        run.font.color.rgb = RGBColor(128, 0, 128) # Purple for UI

        p = doc.add_paragraph(item["desc"])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

    # Integration Section
    doc.add_page_break()
    title_integration = doc.add_heading('Backend-Frontend Integration', 0)
    title_integration.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    
    integration_text = (
        "The connection between the Python Backend and React Frontend is established through RESTful API communication.\n\n"
        "1. API Endpoint: The Backend (FastAPI) exposes a POST endpoint '/analyze-video' which accepts a JSON payload containing the YouTube URL.\n"
        "2. CORS (Cross-Origin Resource Sharing): Since the frontend runs on port 5173 and the backend on 8000, we configured 'CORSMiddleware' in 'api.py' to allow browser requests across these different origins.\n"
        "3. HTTP Client: The Frontend uses 'axios', a promise-based HTTP client, to send asynchronous requests to 'http://127.0.0.1:8000/analyze-video'.\n"
        "4. Data Flow: \n"
        "   - User pastes URL in React Frontend -> \n"
        "   - Frontend sends POST request to Backend -> \n"
        "   - Backend fetches comments from YouTube -> \n"
        "   - Backend runs DistilBERT model inference -> \n"
        "   - Backend returns JSON data (labels, confidence) -> \n"
        "   - Frontend updates state and visualizes results."
    )
    doc.add_paragraph(integration_text)

    # Extensions Section
    doc.add_page_break()
    title_ext = doc.add_heading('Recommended Development Tools & Extensions', 0)
    title_ext.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_paragraph('To efficiently run, debug, and develop this full-stack application (Python Backend + React Frontend), the following VS Code extensions and tools are highly recommended.')

    extensions_info = [
        {
            "name": "Python (Verified by Microsoft)",
            "desc": "Essential for backend development. It provides rich support for the Python language, including IntelliSense (auto-completion), linting, debugging, code navigation, and code formatting. It is crucial for running the FastAPI server and managing virtual environments."
        },
        {
            "name": "Pylance",
            "desc": "A performant, feature-rich language server for Python in VS Code. It provides fast and accurate type checking, auto-imports, and detailed tooltips, which helps prevent bugs in the complex detailed logic (e.g., in 'inference.py')."
        },
        {
            "name": "ES7+ React/Redux/React-Native snippets",
            "desc": "A productivity extension for frontend development. It allows developers to quickly generate boilerplate React components (like 'rafce') and import statements using short commands, speeding up the creation of UI components."
        },
        {
            "name": "Tailwind CSS IntelliSense",
            "desc": "Vital for this project's UI styling. It provides autocomplete, syntax highlighting, and linting for Tailwind CSS classes. This ensures that utility classes (e.g., 'bg-gray-900', 'text-white') are typed correctly and allows you to see the CSS values on hover."
        },
        {
            "name": "Prettier - Code formatter",
            "desc": "An opinionated code formatter that enforces a consistent style across the entire codebase (both JavaScript/React and JSON files). It automatically formats code on save, keeping the project structure clean and readable."
        },
        {
            "name": "Thunder Client / Postman",
            "desc": "API Testing tools. While not strictly an extension for 'running' the code, these are used to manually test the Backend API endpoints (like POST /predict or /analyze-video) independently of the frontend to ensure they return the correct JSON structure."
        }
    ]

    for item in extensions_info:
        h = doc.add_heading(item["name"], level=1)
        run = h.runs[0]
        run.font.color.rgb = RGBColor(255, 140, 0) # Dark Orange

        p = doc.add_paragraph(item["desc"])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

    # Save
    output_dir = "presentation"
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "ex.docx")
    doc.save(output_path)
    print(f"Document saved to: {output_path}")

if __name__ == "__main__":
    create_document()
